// playwright.config.ts
import { defineConfig } from "@playwright/test";
import 'dotenv/config';

export default defineConfig({
  testDir: "./tests",

  timeout: 90_000,

  use: {
    // Reuse the authenticated session generated by global-setup
    storageState: process.env.SF_STORAGE_STATE ?? "storageState.json",
    baseURL: process.env.SF_MYDOMAIN_HOST,
    trace: "retain-on-failure",
    screenshot: "only-on-failure",
    video: "retain-on-failure"
  },

  projects: [
    // { name: 'Chromium', use: { browserName: 'chromium' } },
    { name: 'Firefox', use: { browserName: 'firefox' } },
    // { name: 'Webkit', use: { browserName: 'webkit' } }
  ],


  globalSetup: './scripts/global-setup.ts',

  // Paranoid: avoid parallel tests hitting setup simultaneously at first run
  fullyParallel: false,
});