// playwright.config.ts
import { defineConfig } from "@playwright/test";
import 'dotenv/config';

export default defineConfig({
  //testDir: "./tests",
  projects: [
    {
      name: 'main-tests',
      testDir: './tests/main',
      use: { browserName: 'chromium' }
    },
    {
      name: 'post-run-tests',
      testDir: './tests/post-run',
      dependencies: ['main-tests'],
      use: { browserName: 'chromium' }
    }
  ],


  timeout: 90_000,

  reporter: [
    ['html', {
      open: 'never',          // 'never' (CI), 'on-failure', or 'always'
      outputFolder: 'playwright-report' // default is 'playwright-report'
    }],
    ['allure-playwright'],
  ],

  expect: {
    timeout: 30000,
  },

  fullyParallel: true,
  retries: 2,
  workers: 1,

  use: {
    // Reuse the authenticated session generated by global-setup
    storageState: process.env.SF_STORAGE_STATE ?? "storageState.json",
    baseURL: process.env.SF_MYDOMAIN_HOST,
    trace: "retain-on-failure",
    screenshot: "only-on-failure",
    video: "retain-on-failure",
    actionTimeout: 20000, // 20 seconds for all click
    //navigationTimeout: 10000,
  },


  globalSetup: './scripts/global-setup.ts',

  // Paranoid: avoid parallel tests hitting setup simultaneously at first run
});